// data.jsx — sample data for FlatNest (Dhaka market, BDT pricing)

const FN_LISTINGS = [
  {
    id: 'l1',
    title: 'Sunlit 2BR Studio in Banani',
    area: 'Banani',
    distance: '1.2 km',
    price: 28000,
    deposit: 56000,
    beds: 2, baths: 2, size: 1100,
    type: 'Family',
    rating: 4.9,
    reviews: 124,
    photos: ['#FFD9A8', '#A8C4D6', '#D4C3B7', '#C9D8B7'],
    photoTint: '#FFD9A8',
    coords: { x: 38, y: 42 },
    owner: { name: 'Tahmid R.', initials: 'TR', verified: true, since: '2022' },
    amenities: ['Wifi', 'Parking', 'Gas', 'Lift', 'Generator', 'Gym'],
    description: 'Bright corner unit on the 6th floor with park view. Two balconies, semi-furnished, gas line for cooking, 24/7 backup generator. Walking distance to Banani lake and Road 11 cafés.',
  },
  {
    id: 'l2',
    title: 'Modern Studio near Gulshan 2',
    area: 'Gulshan',
    distance: '2.4 km',
    price: 18500,
    deposit: 37000,
    beds: 1, baths: 1, size: 520,
    type: 'Bachelor',
    rating: 4.7,
    reviews: 38,
    photos: ['#C4B5A0', '#D8C5B0', '#A8B4C0'],
    photoTint: '#C4B5A0',
    coords: { x: 64, y: 28 },
    owner: { name: 'Nazia K.', initials: 'NK', verified: true, since: '2023' },
    amenities: ['Wifi', 'Lift', 'Generator', 'Furnished'],
    description: 'Cozy studio perfect for working professionals. Includes desk, queen bed, induction stove, water filter.',
  },
  {
    id: 'l3',
    title: 'Spacious 3BR Family Flat',
    area: 'Dhanmondi',
    distance: '4.1 km',
    price: 42000,
    deposit: 84000,
    beds: 3, baths: 3, size: 1650,
    type: 'Family',
    rating: 4.8,
    reviews: 87,
    photos: ['#B8D4C8', '#C8D8C0'],
    photoTint: '#B8D4C8',
    coords: { x: 22, y: 64 },
    owner: { name: 'Rafiq A.', initials: 'RA', verified: true, since: '2021' },
    amenities: ['Wifi', 'Parking', 'Gas', 'Lift', 'Generator', 'Servant Qtr'],
    description: 'Quiet road, third floor, full south-facing balcony. Two car parking included.',
  },
  {
    id: 'l4',
    title: 'Cozy 1BR with Roof Access',
    area: 'Mohakhali DOHS',
    distance: '3.0 km',
    price: 22000,
    deposit: 44000,
    beds: 1, baths: 1, size: 680,
    type: 'Couple',
    rating: 4.6,
    reviews: 19,
    photos: ['#E8C9A0', '#D4B898'],
    photoTint: '#E8C9A0',
    coords: { x: 52, y: 18 },
    owner: { name: 'Sumaiya H.', initials: 'SH', verified: false, since: '2024' },
    amenities: ['Wifi', 'Roof', 'Lift'],
    description: 'Top floor unit with private roof access. Great for plants and small gatherings.',
  },
  {
    id: 'l5',
    title: 'Bright 2BR near Bashundhara Gate',
    area: 'Bashundhara R/A',
    distance: '5.8 km',
    price: 24000,
    deposit: 48000,
    beds: 2, baths: 2, size: 950,
    type: 'Family',
    rating: 4.7,
    reviews: 52,
    photos: ['#B4C8D8', '#A0BCD0'],
    photoTint: '#B4C8D8',
    coords: { x: 78, y: 56 },
    owner: { name: 'Imran S.', initials: 'IS', verified: true, since: '2022' },
    amenities: ['Wifi', 'Parking', 'Gas', 'Lift', 'Generator'],
    description: 'Eight-storied building, fifth floor, two side balconies.',
  },
  {
    id: 'l6',
    title: 'Compact Studio for Students',
    area: 'Mirpur 10',
    distance: '6.7 km',
    price: 11500,
    deposit: 23000,
    beds: 1, baths: 1, size: 380,
    type: 'Student',
    rating: 4.4,
    reviews: 11,
    photos: ['#D8C0A8', '#C8B098'],
    photoTint: '#D8C0A8',
    coords: { x: 14, y: 30 },
    owner: { name: 'Faria M.', initials: 'FM', verified: false, since: '2024' },
    amenities: ['Wifi', 'Gas'],
    description: 'Affordable single-room studio with attached bath. Bills extra.',
  },
];

const FN_CHATS = [
  {
    id: 'c1',
    listing: 'l1',
    name: 'Tahmid R.',
    initials: 'TR',
    last: 'Sure, you can visit Saturday after 4 PM 👋',
    time: '12:42',
    unread: 2,
    online: true,
    color: '#FFD9A8',
    messages: [
      { from: 'them', text: 'Hi! Thanks for your interest in the Banani flat.', time: '11:02' },
      { from: 'me',   text: 'Is the unit still available? Looking to move in by next month.', time: '11:14' },
      { from: 'them', text: 'Yes, available from Dec 1. The gas line is active and there\'s a backup generator for the whole building.', time: '11:18' },
      { from: 'me',   text: 'Great. Can I visit this weekend?', time: '12:30' },
      { from: 'them', text: 'Sure, you can visit Saturday after 4 PM 👋', time: '12:42' },
    ],
  },
  {
    id: 'c2',
    listing: 'l2',
    name: 'Nazia K.',
    initials: 'NK',
    last: 'The deposit is two months, refundable.',
    time: 'Yesterday',
    unread: 0,
    online: false,
    color: '#C4B5A0',
  },
  {
    id: 'c3',
    listing: 'l3',
    name: 'Rafiq A.',
    initials: 'RA',
    last: 'I can drop the rent by 2k for a 2-year lease.',
    time: 'Mon',
    unread: 1,
    online: true,
    color: '#B8D4C8',
  },
  {
    id: 'c4',
    listing: 'l5',
    name: 'Imran S.',
    initials: 'IS',
    last: 'You: Thanks, I\'ll let you know tomorrow.',
    time: 'Sun',
    unread: 0,
    online: false,
    color: '#B4C8D8',
  },
];

const FN_NOTIFICATIONS = [
  { id: 'n1', kind: 'message', title: 'Tahmid sent you a message', body: '"Sure, you can visit Saturday after 4 PM"', time: '2m', unread: true },
  { id: 'n2', kind: 'price',   title: 'Price drop on a saved flat', body: 'Modern Studio near Gulshan 2 · ৳18,500 → ৳17,000', time: '1h', unread: true },
  { id: 'n3', kind: 'match',   title: '3 new flats match your search', body: 'Banani · 2BR · under ৳30,000', time: '3h', unread: false },
  { id: 'n4', kind: 'system',  title: 'Identity verified ✓', body: 'You can now message owners directly.', time: 'Yesterday', unread: false },
  { id: 'n5', kind: 'message', title: 'Rafiq sent you a message', body: '"I can drop the rent by 2k for a 2-year lease."', time: 'Mon', unread: false },
];

const FN_FILTER_CHIPS = ['All', 'Family', 'Bachelor', 'Student', 'Furnished', 'Under ৳20k', 'Banani', 'Gulshan'];

Object.assign(window, { FN_LISTINGS, FN_CHATS, FN_NOTIFICATIONS, FN_FILTER_CHIPS });
